# Generated by Django 5.0.6 on 2024-05-16 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="aboutme",
            options={"verbose_name": "About Me", "verbose_name_plural": "About Me"},
        ),
        migrations.AlterModelOptions(
            name="contactinquiry",
            options={
                "verbose_name": "Contact Inquiry",
                "verbose_name_plural": "Contact Inquiries",
            },
        ),
    ]
