# Generated by Django 5.0.6 on 2024-05-25 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0002_alter_aboutme_options_alter_contactinquiry_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="aboutme",
            name="avatar",
            field=models.ImageField(blank=True, upload_to="about_me/avatars/"),
        ),
        migrations.CreateModel(
            name="SocialMediaLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("platform", models.CharField(max_length=100)),
                ("url", models.URLField()),
                (
                    "about_me",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_links",
                        to="about.aboutme",
                    ),
                ),
            ],
        ),
    ]
