# Generated by Django 5.0.6 on 2024-05-25 08:48

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0003_aboutme_avatar_socialmedialink"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aboutme", name="summary", field=ckeditor.fields.RichTextField(),
        ),
    ]
