# Generated by Django 5.0.6 on 2024-05-25 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0004_alter_aboutme_summary"),
    ]

    operations = [
        migrations.AddField(
            model_name="aboutme",
            name="subtitle",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
