# Generated by Django 5.0.6 on 2024-05-29 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0006_aboutme_email"),
        ("projects", "0003_alter_category_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactinquiry",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="projects.category",
            ),
        ),
    ]
