# Generated by Django 5.0.2 on 2026-05-09 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0008_aboutme_current_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aboutme",
            name="current_role",
            field=models.CharField(default="Software Developer", max_length=200),
        ),
        migrations.AlterField(
            model_name="aboutme",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="aboutme",
            name="subtitle",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="contactinquiry",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="socialmedialink",
            name="platform",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="socialmedialink",
            name="url",
            field=models.URLField(max_length=500),
        ),
    ]
