# Generated by Django 5.0.6 on 2024-05-16 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_codingskill_project_skills_used"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Category", "verbose_name_plural": "Categories"},
        ),
    ]
