# Generated by Django 5.0.6 on 2024-12-28 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_alter_category_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="display_order",
            field=models.IntegerField(default=0, help_text="Order in which projects are displayed (lower numbers appear first)"),
        ),
    ]

