# Generated by Django 5.0.2 on 2026-05-09 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_project_display_order"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={"ordering": ["display_order", "-start_date", "title"]},
        ),
    ]
