# Generated by Django 5.0.2 on 2026-05-09 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0005_alter_project_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name="codingskill",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="project",
            name="caption",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="project",
            name="organisation",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="project",
            name="title",
            field=models.CharField(max_length=200),
        ),
    ]
