# Generated by Django 5.0.2 on 2026-05-09 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0006_alter_category_name_alter_category_slug_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="highlights",
            field=models.JSONField(
                blank=True, default=list, help_text="3-5 short skim bullets"
            ),
        ),
    ]
