# Generated by Django 5.0.6 on 2024-05-16 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("opensource", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="opensourcecontribution", name="end_date",),
        migrations.RemoveField(model_name="opensourcecontribution", name="issue",),
        migrations.RemoveField(model_name="opensourcecontribution", name="start_date",),
        migrations.AddField(
            model_name="opensourcecontribution",
            name="pr_link",
            field=models.URLField(blank=True),
        ),
    ]
