# Generated by Django 5.0.6 on 2024-05-28 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("opensource", "0003_opensourceprojectimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="opensourceprojectimage",
            name="image",
            field=models.ImageField(upload_to="open_source_project_images/"),
        ),
    ]
