# Generated by Django 5.0.6 on 2024-05-29 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("opensource", "0005_opensourceproject_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="opensourceproject",
            name="caption",
            field=models.CharField(default="Open Source Project", max_length=150),
        ),
        migrations.AlterField(
            model_name="opensourcecontribution",
            name="open_source_project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contributions",
                to="opensource.opensourceproject",
            ),
        ),
    ]
