# Generated by Django 5.0.2 on 2026-05-09 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("opensource", "0006_opensourceproject_caption_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contributiontype",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="contributiontype",
            name="slug",
            field=models.SlugField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name="opensourceproject",
            name="caption",
            field=models.CharField(default="Open Source Project", max_length=500),
        ),
        migrations.AlterField(
            model_name="opensourceproject",
            name="name",
            field=models.CharField(max_length=200),
        ),
    ]
