# Generated by Django 5.0.6 on 2024-05-15 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("experiences", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workexperience",
            name="location",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
