# Generated by Django 5.0.6 on 2024-05-28 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("experiences", "0003_workexperience_skills_used"),
    ]

    operations = [
        migrations.AddField(
            model_name="workexperience",
            name="website",
            field=models.URLField(blank=True),
        ),
    ]
