# Generated by Django 5.0.6 on 2024-12-28 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("experiences", "0004_workexperience_website"),
    ]

    operations = [
        migrations.AddField(
            model_name="workexperience",
            name="company_logo",
            field=models.ImageField(blank=True, null=True, upload_to="company_logos/"),
        ),
    ]

