# Generated by Django 5.0.2 on 2026-05-09 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("experiences", "0005_workexperience_company_logo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workexperience",
            name="company",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="workexperience",
            name="location",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="workexperience",
            name="title",
            field=models.CharField(max_length=200),
        ),
    ]
